VeterinariaESI/Controllers/EjemploController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace VeterinariaESI.Controllers
{
    public class EjemploController : Controller
    {
        // GET: Ejemplo
        //privat   proxy = new SocratesWS.SocratesServiceClient();

        //private VetServiceSAOP.VetServiceClient proxy = new VetServiceSAOP.VetServiceClient();

        private VetServiceWSSOAP.VetServiceClient proxy = new VetServiceWSSOAP.VetServiceClient();


        public ActionResult Index()
        {

            string ruta2 = "C:\\Users\\Kevin Anyoza\\Documents\\GitHub\\esi4\\VetMensajeria\\bin\\Release\\";
            string ejecutable2 = Path.Combine(ruta2, "VetMensajeria.exe");

            var proc2 = System.Diagnostics.Process.Start(ejecutable2);
            proc2.CloseMainWindow();
            proc2.Close();

            VetServiceWSSOAP.Mensaje[] mensajesCreados = proxy.ListarMensajes();
            ViewData["Message"] = "Listado de Mensajes";
            ViewBag.Titulo1 = "Codigo";
            ViewBag.Titulo2 = "Correo ";
            ViewBag.Titulo3 = "Mensaje";
           
            return View(mensajesCreados);
        }


        //public descargarmensajes()
        //{ 

        //}


    }
}

VeterinariaESI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace VeterinariaESI.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        [HttpPost]
        public ActionResult Index(string correo, string mensaje)
        {
            //Process programa = null;
            //ProcessStartInfo info = null;
            string ruta = "C:\\Users\\Kevin Anyoza\\Documents\\GitHub\\esi4\\VetEnvioMensaje\\bin\\Release\\";
            string ejecutable = Path.Combine(ruta, "VetEnvioMensaje.exe");

            string parametros = correo + " \"" + mensaje + "\"";

            var proc = System.Diagnostics.Process.Start(ejecutable, parametros);
            proc.CloseMainWindow();
            proc.Close();
            //info = new ProcessStartInfo(ExeyParams);
            //programa = Process.Start(info);
            //System.Diagnostics.Process process = new System.Diagnostics.Process();
            //process.StartInfo.FileName = "cmd";

           

            return View();
        }


    }
}

VeterinariaESI/Controllers/VentasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.IO;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using VeterinariaESI.Models;
using VeterinariaESI.Dominio;

namespace VeterinariaESI.Controllers
{
    public class VentasController : Controller
    {
        private VetDSDEntities db = new VetDSDEntities();

        // GET: Ventas
        //public ActionResult Index()
        //{
        //    var venta = db.Venta.Include(v => v.Cliente).Include(v => v.Usuario);
        //    return View(venta.ToList());
        //}

        // GET: Horarios
        public ActionResult Index()
        {
            HttpWebRequest request = (HttpWebRequest)WebRequest.
                    Create("http://localhost:34974/VetService.svc/ventasvet");
            request.Method = "GET";
            HttpWebResponse response = (HttpWebResponse)request.GetResponse();
            StreamReader reader = new StreamReader(response.GetResponseStream());
            string tramaJson = reader.ReadToEnd();
            JavaScriptSerializer js = new JavaScriptSerializer();
            List<Ventas> ventasObtenidos = js.Deserialize<List<Ventas>>(tramaJson);

            ViewData["Message"] = "Listado de horarios";
            ViewBag.Titulo01 = "idventa ";
            ViewBag.Titulo02 = "idusuario";
            ViewBag.Titulo03 = "fecha";
            ViewBag.Titulo04 = "idcliente";
            ViewBag.Titulo05 = "codigoventa";
    

            return View(ventasObtenidos);
        }

        // GET: Ventas/Details/5
        //public ActionResult Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Venta venta = db.Venta.Find(id);
        //    if (venta == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(venta);
        //}

        // GET: Ventas/Create
        //public ActionResult Create()
        //{
        //    ViewBag.IDCliente = new SelectList(db.Cliente, "IDCliente", "Nombres");
        //    ViewBag.IDUsuario = new SelectList(db.Usuario, "IDUsuario", "Nombre");
        //    return View();
        //}

        // POST: Ventas/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "IDVenta,IDCliente,Fecha,IDUsuario")] Venta venta)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Venta.Add(venta);
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }

        //    ViewBag.IDCliente = new SelectList(db.Cliente, "IDCliente", "Nombres", venta.IDCliente);
        //    ViewBag.IDUsuario = new SelectList(db.Usuario, "IDUsuario", "Nombre", venta.IDUsuario);
        //    return View(venta);
        //}

        // GET: Ventas/Edit/5
        //public ActionResult Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Venta venta = db.Venta.Find(id);
        //    if (venta == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    ViewBag.IDCliente = new SelectList(db.Cliente, "IDCliente", "Nombres", venta.IDCliente);
        //    ViewBag.IDUsuario = new SelectList(db.Usuario, "IDUsuario", "Nombre", venta.IDUsuario);
        //    return View(venta);
        //}

        // POST: Ventas/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit([Bind(Include = "IDVenta,IDCliente,Fecha,IDUsuario")] Venta venta)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(venta).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    ViewBag.IDCliente = new SelectList(db.Cliente, "IDCliente", "Nombres", venta.IDCliente);
        //    ViewBag.IDUsuario = new SelectList(db.Usuario, "IDUsuario", "Nombre", venta.IDUsuario);
        //    return View(venta);
        //}

        // GET: Ventas/Delete/5
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Venta venta = db.Venta.Find(id);
        //    if (venta == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(venta);
        //}

        // POST: Ventas/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    Venta venta = db.Venta.Find(id);
        //    db.Venta.Remove(venta);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        //protected override void Dispose(bool disposing)
        //{
        //    if (disposing)
        //    {
        //        db.Dispose();
        //    }
        //    base.Dispose(disposing);
        //}
    }
}

VeterinariaESI/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

VeterinariaESI/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Envienos un Mensaje";
}
<h2>@ViewBag.Title.</h2>


<div class="row m-3" style="margin-top: 20px;">
    <form action="/Home/Index" method="post">
        <div class="form-group">
            <label for="exampleInputEmail1">Email address</label>
            <input type="email" name="correo" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">

        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">Mensaje</label>
            <textarea class="form-control" rows="5" name="mensaje"></textarea>
        </div>
       
        <button type="submit" class="btn btn-primary">Enviar</button>
      
    </form>
</div>


@*<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>*@

VeterinariaESI/Views/Home/Index.cshtml
@{
    ViewBag.Title = "SANICAN";
}

    <div class="" style="margin-top:50px;">
        <div class="col-lg-3 col-sm-6 text-center m-3">
            <a href="@Url.Action("Index", "clientes")">
                <img class="rounded-circle img-fluid d-block mx-auto" src="https://icon-icons.com/icons2/1154/PNG/256/1486564400-account_81513.png" />
            </a>
            <h3>Clientes</h3>
        </div>

        <div class="col-lg-3 col-sm-6 text-center mb-4">
            <a href="@Url.Action("Index", "Ventas")">
                <img class="rounded-circle img-fluid d-block mx-auto" src="https://icon-icons.com/icons2/2407/PNG/256/itch_icon_146025.png" />
            </a>
            <h3>Ventas</h3>
        </div>

        <div class="col-lg-3 col-sm-6 text-center mb-4">
            <a href="@Url.Action("Index", "Ejemplo")">
                <img class="rounded-circle img-fluid d-block mx-auto" src="https://icon-icons.com/icons2/1154/PNG/256/1486564410-chat_81504.png" />
            </a>
            <h3>Mensajeria</h3>
        </div>
    </div>

    @*<div class="jumbotron">
            <h1>ASP.NET</h1>
            <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
            <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
        </div>*@

    <div class="row">
        @*<div class="col-md-4">
                <h2>Getting started</h2>
                <p>
                    ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                    enables a clean separation of concerns and gives you full control over markup
                    for enjoyable, agile development.
                </p>
                <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
            </div>
            <div class="col-md-4">
                <h2>Get more libraries</h2>
                <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
                <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
            </div>
            <div class="col-md-4">
                <h2>Web Hosting</h2>
                <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
                <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
            </div>*@
    </div>